#!/bin/bash

LOCKFILE=$HOME/.ssh/config.lock
COUNTER=$HOME/.ssh/ssh_session_count
LOGFILE=$HOME/.ssh/rc.log

# Perform entry op with lock
flock $LOCKFILE $HOME/.ssh/scripts/entry.sh >> $LOGFILE

SSHD_PID=$(ps -o ppid= -p $PPID | tr -d ' ')
echo "$(date): Monitoring SSHD_PID: $SSHD_PID" >> /tmp/ssh_rc_debug.log
nohup $HOME/.ssh/scripts/monitor.sh $SSHD_PID $LOCKFILE >> $LOGFILE 2>&1 &
